In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import matplotlib.pyplot as plt


In [ ]:
db = pd.read_csv('/content/drive/MyDrive/broadway py w ai/Student Performance Multiple Linear Regression.csv')
db.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [ ]:
db.dropna(inplace=True)


In [ ]:
x = db[['Hours Studied','Previous Scores','Sleep Hours','Sample Question Papers Practiced']]
y = db['Performance Index']

In [ ]:
x.head()

Hours Studied  Previous Scores  Sleep Hours  \
0              7               99            9   
1              4               82            4   
2              8               51            7   
3              5               52            5   
4              7               75            8   

   Sample Question Papers Practiced  
0                                 1  
1                                 2  
2                                 2  
3                                 2  
4                                 5

In [ ]:
scaler = StandardScaler()
x=scaler.fit_transform(x)

In [ ]:
x

array([[ 0.77518771,  1.70417565,  1.45620461, -1.24975394],
       [-0.38348058,  0.72391268, -1.49229423, -0.90098215],
       [ 1.16141048, -1.06362569,  0.27680507, -0.90098215],
       ...,
       [ 0.38896495,  0.7815752 ,  0.86650484,  0.1453332 ],
       [ 1.54763324,  1.5888506 ,  0.27680507, -1.59852572],
       [ 0.77518771,  0.26261245,  0.86650484, -1.24975394]])

In [ ]:
v = db['Extracurricular Activities']
v.head()

0    Yes
1     No
2    Yes
3    Yes
4     No
Name: Extracurricular Activities, dtype: object

In [ ]:
for i in range(len(v)):
  if v[i] == 'Yes':
    v[i] = 1
  else:
    v[i] = 0


Streaming output truncated to the last 5000 lines.
/tmp/ipython-input-3685335910.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  v[i] = 1
/tmp/ipython-input-3685335910.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  v[i] = 0
/tmp/ipython-input-3685335910.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  v[i] = 1
/tmp/ipython-input-3685335910.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from 

In [ ]:
x = pd.DataFrame(x)

In [ ]:
x[4]=v

In [ ]:
x.head()

0         1         2         3  4
0  0.775188  1.704176  1.456205 -1.249754  1
1 -0.383481  0.723913 -1.492294 -0.900982  0
2  1.161410 -1.063626  0.276805 -0.900982  1
3  0.002742 -1.005963 -0.902594 -0.900982  1
4  0.775188  0.320275  0.866505  0.145333  0

In [ ]:
y.head()

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

In [ ]:
model = Sequential([
    Input(shape=(5,)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1)

])

In [ ]:
model.compile(optimizer='adam', loss='mae')

In [ ]:
fmodel = model.fit(xtrain, ytrain, epochs=15)

Epoch 1/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 44.6648
Epoch 2/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5.7542
Epoch 3/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3.7806
Epoch 4/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.3372
Epoch 5/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.8950
Epoch 6/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7992
Epoch 7/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7757
Epoch 8/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7379
Epoch 9/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6808
Epoch 10/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.7204
Epoch 11/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6784
Epoch 12/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6616
Epoch 13/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6782
Epoch 14/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6942
Epoch 15/15
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - l

In [ ]:
model.evaluate(xtest, ytest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.7156


1.7131444215774536

In [ ]:
# Prediction

In [ ]:
hs = float(input('Hours Studied: '))
ps = float(input('Previous Scores: '))
sh = float(input('Sleep Hours: '))
sq = float(input('Sample Question Papers Practiced: '))
ea_str = input('Extracurricular Activities (Yes/No): ').lower()
ea = 1 if ea_str == 'yes' else 0

Hours Studied: 6
Previous Scores: 78
Sleep Hours: 2
Sample Question Papers Practiced: 5
Extracurricular Activities (Yes/No): no


In [ ]:
hs1,ps1,sh1,sq1 = hs,ps,sh,sq

In [ ]:
scaled_value = scaler.transform([[hs1,ps1,sh1,sq1]])
scaled_value

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.38896495,  0.49326256, -2.67169377,  0.1453332 ]])

In [ ]:
input_data = np.append(scaled_value,np.array([[ea]]))
input_data

array([ 0.38896495,  0.49326256, -2.67169377,  0.1453332 ,  0.        ])

In [ ]:
input_data.shape

(5,)

In [ ]:
type(input_data)

numpy.ndarray

In [ ]:
result = model.predict(np.array([input_data]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


In [ ]:
result

array([[64.16981]], dtype=float32)